// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCasIzRbi-3W3cPknt7Wz5vHvMRYgjsEgA',
    appId: '1:504814620641:web:1b4a4784b3a247f31a0ca0',
    messagingSenderId: '504814620641',
    projectId: 'bulkbuysplitter',
    authDomain: 'bulkbuysplitter.firebaseapp.com',
    storageBucket: 'bulkbuysplitter.firebasestorage.app',
    measurementId: 'G-PXT5QX592Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANcpyBXugVrlfbhJYF9Ik_SciLr-sBjbA',
    appId: '1:504814620641:android:b1bc9418c9914d531a0ca0',
    messagingSenderId: '504814620641',
    projectId: 'bulkbuysplitter',
    storageBucket: 'bulkbuysplitter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTmi_A97KWdZ5bgMq1LxPOosmDNrY4X4s',
    appId: '1:504814620641:ios:49c3cfe08e9f6bbc1a0ca0',
    messagingSenderId: '504814620641',
    projectId: 'bulkbuysplitter',
    storageBucket: 'bulkbuysplitter.firebasestorage.app',
    androidClientId: '504814620641-7fnt9v15r6gm6ic53cg7havkvd8ij0lg.apps.googleusercontent.com',
    iosBundleId: 'dev.flutter.plugins.googleSignInExample',
  );

}